services:
  - type: web
    name: pdf-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
