
# render.yaml - Конфігурація для Render
services:
  - type: web
    name: pdf-converter
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: pdf-storage
      mountPath: /opt/render/project/src/temp
      sizeGB: 1
