# render.yaml - альтернативна версія без Docker
services:
  - type: web
    name: pdf-service
    env: python
    region: oregon
    plan: free
    
    # Спроба встановити залежності через buildCommand
    buildCommand: |
      echo "=== Starting build process ==="
      echo "Installing Python dependencies..."
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      echo "=== Build process complete ==="

    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"

    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        generateValue: true
      # Видаляємо TESSDATA_PREFIX поки не підтвердимо наявність Tesseract
      
# Додаємо окремий сервіс для перевірки можливості встановлення Tesseract
# (це експериментальний підхід)
  - type: background
    name: tesseract-setup
    env: python
    region: oregon
    plan: free
    buildCommand: |
      echo "Attempting to install Tesseract..."
      # Цей сервіс буде спробувати встановити Tesseract
      # але background сервіси мають обмежені можливості
    startCommand: "echo 'Tesseract setup service' && sleep infinity"
