services:
  - type: web
    name: pdf-service
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Update package lists
      apt-get update -y
      
      # Install basic dependencies first
      apt-get install -y wget curl software-properties-common
      
      # Install Tesseract OCR with language packs
      apt-get install -y tesseract-ocr tesseract-ocr-ukr tesseract-ocr-eng tesseract-ocr-rus
      
      # Install fonts for better text rendering
      apt-get install -y fonts-dejavu fonts-dejavu-core fonts-dejavu-extra
      apt-get install -y fonts-liberation fonts-noto fonts-noto-core
      apt-get install -y fontconfig
      
      # Install WeasyPrint system dependencies
      apt-get install -y libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
      apt-get install -y libfontconfig1 libcairo2 libgdk-pixbuf2.0-0 
      apt-get install -y libffi-dev shared-mime-info libxml2-dev libxslt1-dev
      
      # Additional libraries for image processing
      apt-get install -y libjpeg-dev libpng-dev libtiff-dev
      
      # Clean up
      apt-get clean
      rm -rf /var/lib/apt/lists/*
      
      # Verify Tesseract installation
      tesseract --version
      tesseract --list-langs
      
      # Install Python dependencies
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
    envVars:
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata/
      - key: PYTHONPATH  
        value: /opt/render/project/src
      - key: DEBIAN_FRONTEND
        value: noninteractive
      - key: PORT
        generateValue: true
