services:
  - type: web
    name: pdf-service
    env: python
    buildCommand: |
      # Встановлюємо системні залежності
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-ukr tesseract-ocr-eng
      apt-get install -y fonts-dejavu fonts-liberation
      
      # Встановлюємо Python залежності
      pip install -r requirements.txt
    startCommand: python -m app.main
    plan: free
    envVars:
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata/
      - key: PYTHONPATH
        value: /opt/render/project/src
